name: Autofill PR description

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'Pull request number'
        required: true
        type: string
      pull_request_url:
        description: 'Externally reachable pull request URL used by the action'
        required: false
        default: '__AUTO_GENERATE_PR_URL__'
        type: string
      overwrite_description:
        description: 'Whether to overwrite the existing description'
        required: false
        type: boolean
        default: true
      azure_openai_deployment:
        description: 'Azure OpenAI deployment name'
        required: false
        type: string
        default: ''
    secrets:
      AZURE_OPENAI_API_KEY:
        required: true
      AZURE_OPENAI_ENDPOINT:
        required: false
      AZURE_OPENAI_VERSION:
        required: false

env:
  PR_NUMBER: ${{ inputs.pr_number || github.event.number }}
  PULL_REQUEST_URL: ${{ inputs.pull_request_url == '__AUTO_GENERATE_PR_URL__' && format('https://pr{0}.api.kerberos.lol', github.event.number) || inputs.pull_request_url }}
  
jobs:
  openai-pr-description:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write

    steps:
      - name: Autofill PR description using Azure OpenAI
        uses: uug-ai/workflows/.github/actions/pr-description@main
        with:
          github_token: ${{ github.token }}
          pull_request_number: ${{ env.PR_NUMBER }}
          pull_request_url: ${{ env.PULL_REQUEST_URL }}
          overwrite_description: ${{ inputs.overwrite_description }}
          azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT || vars.AZURE_OPENAI_ENDPOINT }}
          azure_openai_version: ${{ secrets.AZURE_OPENAI_VERSION || vars.AZURE_OPENAI_VERSION }}
          azure_openai_deployment: ${{ inputs.azure_openai_deployment || secrets.AZURE_OPENAI_DEPLOYMENT || secrets.OPENAI_MODEL || vars.AZURE_OPENAI_DEPLOYMENT || vars.OPENAI_MODEL }}
