name: Autofill PR description

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'Pull request number'
        required: true
        type: string
      pull_request_url:
        description: 'Externally reachable pull request URL used by the action'
        required: false
        default: '__AUTO_GENERATE_PR_URL__'
        type: string
      overwrite_description:
        description: 'Whether to overwrite the existing description'
        required: false
        type: boolean
        default: true
    secrets:
      AZURE_OPENAI_API_KEY:
        required: true
      AZURE_OPENAI_ENDPOINT:
        required: false
      AZURE_OPENAI_VERSION:
        required: false

env:
  PROJECT: ${{ github.event.repository.name }}
  PR_NUMBER: ${{ inputs.pr_number || github.event.number }}
  PULL_REQUEST_URL: ${{ inputs.pull_request_url == '__AUTO_GENERATE_PR_URL__' && format('https://pr{0}.api.kerberos.lol', github.event.number) || inputs.pull_request_url }}
  
jobs:
  openai-pr-description:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Autofill PR description if empty using OpenAI
        uses: cedricve/azureopenai-pr-description@master
        with:
          github_token: ${{ github.token }}
          azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY }}
          azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT || vars.AZURE_OPENAI_ENDPOINT }}
          azure_openai_version: ${{ secrets.AZURE_OPENAI_VERSION || vars.AZURE_OPENAI_VERSION }}
          openai_model: ${{ vars.OPENAI_MODEL || 'gpt-4o' }}
          pull_request_url: ${{ env.PULL_REQUEST_URL }}
          overwrite_description: ${{ inputs.overwrite_description != false }}
